# Generated by Django 3.2.13 on 2022-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='patent',
            name='app_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='app_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='app_number',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='astr_cont',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='big_drawing',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='drawing',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='open_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='open_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='pub_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='reg_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='reg_status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patent',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
