# Generated by Django 3.2.13 on 2022-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
